#!/bin/bash

make clean
make 
cp libcrypto.so ~/tftp/
cp libcrypto.so codeblocks/tets_lib_crypto/
cp main.o codeblocks/tets_lib_crypto/obj/Debug
date
arch_date=$(date +%s)
tar -cjf ../bkp/kpin_crypto-$arch_date.tar.bz2 .

